[env]
name         = "dev"
debug        = true
http_code    = "json"
ws_code      = "json"
bs_code      = "json"

[server]
network_interface = "en0"
bind_interface    = false
use_interface_ip  = true

[server.grpc]
host              = "0.0.0.0"
port              = 11081

[server.http]
host              = "0.0.0.0"
port              = 11080
charset           = "UTF-8"
gzip              = true
pprof             = true

[server.http.websocket]
enable            = true
endpoint          = "/ws"
library           = "/ws.js"
idle_time         = 60

[log]
dir          = "./logs"
prefix       = "juggernaut"
level        = "debug"
time_format  = "2006-01-02 15:04:05.000"
color        = false
terminal     = false
show_ip      = false

[grpc_srv]
idle      = 30
ttl       = 1800
poolsize  = 512

[grpc_srv.servers.juggernaut_protocol_service_gateway]
host      = "127.0.0.1"
port      = 11081