[env]
name         = "dev"
debug        = true
http_code    = "json"
ws_code      = "json"
bs_code      = "json"

[server]
network_interface = "eth0"
bind_interface    = false
use_interface_ip  = true

[server.grpc]
host              = "0.0.0.0"
port              = 1081

[server.http]
host              = "0.0.0.0"
port              = 1080
charset           = "UTF-8"
gzip              = true
pprof             = true

[server.http.websocket]
enable            = true
endpoint          = "/ws"
library           = "/ws.js"
idle_time         = 60